### ISSUE TITLE
TypeError: Cannot read property 'F_OK' of undefined

### ISSUE THREAD

**Issue by drrui** [hexojs/hexo-deployer-git#126] opened 2019-02-03 06:22 UTC
hey,bro, what's wrong with it? thx~
![_20190203142041](https://user-images.githubusercontent.com/24643117/52173409-005f6780-27bf-11e9-83f8-0768d2a2546c.png)

**Comment by drrui** [comment] 2019-02-03 10:53
@YoshinoriN 

{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.8.0"
  },
  "dependencies": {
    "hexo": "^3.7.0",
    "hexo-abbrlink": "^2.0.5",
    "hexo-baidu-url-submit": "0.0.6",
    "hexo-cli": "^1.1.0",
    "hexo-deployer-git": "^1.0.0",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-baidu-sitemap": "^0.1.6",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-sitemap": "^1.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-marked": "^0.3.2",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.1"
  }
}

**Comment by YoshinoriN** [comment] 2019-02-03 11:07
@drrui 
Would you use hexo-deployer-git `0.3.1`?

**Comment by drrui** [comment] 2019-02-03 11:15
@YoshinoriN      
emmmm, there will be another problem...

**Comment by drrui** [comment] 2019-02-03 11:17
when I use hexo-deployer-git 0.3.1, then...
![_20190203191702](https://user-images.githubusercontent.com/24643117/52176040-51378600-27e8-11e9-8d65-1f59614c5d6c.png)

**Comment by galikeoy** [comment] 2019-02-26 18:52
I have a similar problem with you

**Comment by ninja33** [comment] 2019-03-09 16:15
same problem

**Comment by YoshinoriN** [comment] 2019-03-13 14:11
@drrui @galikeoy @ninja33 
This issues caused by nodejs version.
Could you please update your node to higher than 6.3.0? Thanks.

> [fs.access(path[, mode], callback)](https://github.com/hexojs/hexo-fs/pull/7)

**Comment by drrui** [comment] 2019-03-13 15:34
@YoshinoriN   thank you very much！

**Comment by YoshinoriN** [comment] 2019-03-14 08:12
@drrui 
Please close this issue if problem to be solved.
Thanks :)

**Closed** 2019-03-21 12:43 UTC
Labels: question
